### PR TITLE
add in debug language

### PR DESCRIPTION
**Pull request by andymckay**
- use podebug like the marketplace
- remove the generate_ prefix from actions, seemed superflous
- add in a debug flag to process the debug language

### CODE REVIEW

**Comment by andymckay** [comment]
connects to mozilla/payments#87

**Comment by andymckay** [comment]
@muffinresearch have we got the i18n hooked up in payments-ui? I see lots of gettext statements, but not sure whats meant to be working and whats not at this point.

**Comment by muffinresearch** [comment]
> @muffinresearch have we got the i18n hooked up in payments-ui? I see lots of gettext statements, but not sure whats meant to be working and whats not at this point.

No it's just a no-op at the moment. It won't do anything until we start generating the html + localized bundles for each locale and add something to nginx to handle accept-language headers.

**Comment by muffinresearch** [comment]
lgtm r+

**Pull request merged**
